services:
  - type: web
    name: servercasaperto
    env: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/danielclaytonborgtx/server-2
    branch: master
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: "postgresql://casaperto_db_user:4OCoQRRcYqzoiK2fAFGYcru1GzPu9x5L@dpg-cuusq1nnoe9s73anc31g-a.oregon-postgres.render.com/casaperto_db"
